#! /usr/bin/env racket
#lang racket

[require racket/udp]

[define socket [udp-open-socket]]
[udp-bind! socket #f 45638]
[let loop ()
	[let-values ([(size address port) [udp-receive! socket [make-bytes 0]]])
		[displayln address]
		[udp-send-to socket address port [string->bytes/utf-8 address]]
		[loop]]]
