#lang racket

(provide generate-identity)

(require libuuid)

(define names
  (list "Abbadon"
        "Abraxas"
        "Adraen"
        "Agrith-Naar"
        "Aku"
        "Alagai"
        "Alagai'ting"
        "Alastair"
        "Alastor"
        "Algaliarept"
        "Alichino"
        "Amaimon"
        "Andariel"
        "Angel"
        "Anubis"
        "Anyanka"
        "Anzu"
        "Archimonde"
        "Artery"
        "Asmodeus"
        "Asura"
        "Aurastys"
        "Azal"
        "Azazeal"
        "Azazel"
        "Azmodan"
        "Azrael"
        "Azura"
        "Baal"
        "Babau"
        "Bacarra"
        "Bal'lak"
        "Balor"
        "Balrog"
        "Balthazar"
        "Bandetto"
        "Baphomet"
        "Barakiel"
        "Barbariccia"
        "Barbas"
        "Bartimaeus"
        "Bat'Zul"
        "Be'lakor"
        "Beastie"
        "Bebilith"
        "Beelzebub"
        "Beleth"
        "Belfagor"
        "Belial"
        "Belphegor"
        "Belthazor"
        "Berry"
        "Betelguese"
        "Bhaal"
        "Blackheart"
        "Cacodemon"
        "Cadaver"
        "Cagnazzo"
        "Calcabrina"
        "Calcifer"
        "Castor"
        "Chernabog"
        "Cherry"
        "Chin"
        "Ciriatto"
        "Claude"
        "Cordelia"
        "Crawly"
        "Crowley"
        "Cryto"
        "Cyberdemon"
        "D'Hoffryn"
        "DCI"
        "Dabura"
        "Daeva"
        "Dante"
        "Darius"
        "Darkseid"
        "Decarbia"
        "Delrith"
        "Demonita"
        "Devi"
        "Diablo"
        "Doviculus"
        "Doyle"
        "Draghinazzo"
        "Dretch"
        "Dumain"
        "Duriel"
        "Eligos"
        "Errtu"
        "Etna"
        "Etrigan"
        "Faquarl"
        "Farfarello"
        "Femur"
        "Firebrand"
        "Focalor"
        "Freddy"
        "Furfur"
        "Gaap"
        "Gai"
        "Gary"
        "Glabrezu"
        "Gothmog"
        "Gregor"
        "Halfrek"
        "Har'lakk"
        "Hastur"
        "Hecate"
        "Hell"
        "Hellboy"
        "Hex"
        "Hezrou"
        "Hiei"
        "Him"
        "Hnikarr"
        "Hot"
        "Hyi"
        "Infernal"
        "Inferno"
        "Jabor"
        "Jackal"
        "Jadis"
        "Janemba"
        "Japhrimel"
        "Jaql"
        "Jennifer"
        "Juiblex"
        "K'ril"
        "Kal'Ger"
        "Kek"
        "Khaffit"
        "Khorne"
        "Kil'jaeden"
        "Kitsune"
        "Klippa"
        "Kneesocks"
        "Koakuma"
        "Korrok"
        "Kronos"
        "Laharl"
        "Lamia"
        "Leviathan"
        "Libicocco"
        "Ligur"
        "Lilith"
        "Little"
        "Loki"
        "Longhorn"
        "Lorne"
        "Lucifer"
        "Mal'Ganis"
        "Malacoda"
        "Maledict"
        "Malfegor"
        "Malice"
        "Malzahar"
        "Mammon"
        "Mancubus"
        "Mannoroth"
        "Marilith"
        "Masselin"
        "Mayhem"
        "Meg"
        "Mehrunes"
        "Melkor"
        "Mephisto"
        "Mephistopheles"
        "Moloch"
        "Morgoth"
        "Morningstar"
        "N'zall"
        "Nadia"
        "Nalfeshnee"
        "Nanatoo"
        "Negaren"
        "Nero"
        "Neuro"
        "Newt"
        "Nie"
        "Nouda"
        "Nurgle"
        "Omicron"
        "Overlord"
        "Oyashiro"
        "Par'Chin"
        "Pazuzu"
        "Pennywise"
        "Pithius"
        "Psaro"
        "Quasit"
        "Queezle"
        "Qwan"
        "Qweffor"
        "Rakdos"
        "Ramuthra"
        "Randall"
        "Red"
        "Renard"
        "Retriever"
        "Rin"
        "Ronove"
        "Rosier"
        "Rotteen"
        "Rubicante"
        "Ruby"
        "Satan"
        "Sauron"
        "Scanty"
        "Scarlet"
        "Scarmiglione"
        "Scumspawn"
        "Sebastian"
        "Shax"
        "Silitha"
        "Slaanesh"
        "Sonitus"
        "Sparda"
        "Spawn"
        "Spike"
        "Spine"
        "Straga"
        "Succubus"
        "Tempus"
        "Thammaron"
        "The"
        "Tiamat"
        "To'Kash"
        "Toby"
        "Trigon"
        "Truxton"
        "Turok-Han"
        "Tzeentch"
        "Ungoliant"
        "Vein"
        "Vergil"
        "Violator"
        "Vrock"
        "Vulgrim"
        "Vyers"
        "Ware"
        "Wendigo"
        "Wormwood"
        "Yaksha"
        "Yk'Lagor"
        "Zankou"
        "Zepar"
        "Zuul"))

(define (select-random-name)
  (let ([len (length names)])
    (list-ref names (random len))))

(define (generate-name)
  (string-join (list (select-random-name) (select-random-name))))

(define (generate-identity)
  (with-handlers ([exn?
                    (lambda (e)
                      (displayln e)
                      (values (uuid-generate) (generate-name)))])
    (let ([filepath "identity"])
      (if (file-exists? filepath)
        (with-input-from-file filepath
          (lambda () (apply values (file->value filepath))))
        (let ([id (uuid-generate)]
              [name (generate-name)])
          (with-output-to-file filepath
            (lambda () (write (list id name))))
          (values id name))))))
